insert into authors (id, author) values (1, 'Drucie Goodbourn');
insert into authors (id, author) values (2, 'Marcia Aggiss');
insert into authors (id, author) values (3, 'Giovanni Bigg');
insert into authors (id, author) values (4, 'Duffie Eynon');
insert into authors (id, author) values (5, 'Anselma McKennan');
insert into authors (id, author) values (6, 'Кира Герт');
insert into authors (id, author) values (7, 'Clerc Djakovic');
insert into authors (id, author) values (8, 'Stacee Elsy');
insert into authors (id, author) values (9, 'Dorotea Bonhill');

insert into books (author_id, title, priceOld, price) values (1, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, priceOld, price) values (2, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, priceOld, price) values (3, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, priceOld, price) values (4, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, priceOld, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, priceOld, price) values (6, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, priceOld, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, priceOld, price) values (8, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, priceOld, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, priceOld, price) values (1, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, priceOld, price) values (2, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, priceOld, price) values (3, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, priceOld, price) values (4, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, priceOld, price) values (5, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, priceOld, price) values (6, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, priceOld, price) values (7, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, priceOld, price) values (8, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, priceOld, price) values (9, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, priceOld, price) values (1, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, priceOld, price) values (2, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, priceOld, price) values (3, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, priceOld, price) values (4, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, priceOld, price) values (5, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, priceOld, price) values (6, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, priceOld, price) values (7, 'facilitate efficient eyeballs', '$232.30', '$131.48');
